# 模型与设备
model:
  model_path: /mnt/data/model/Qwen2.5-VL-7B-Instruct
  device: cuda          # 或 cpu
  dtype: auto           # torch dtype 字符串或 auto

# 数据集位置
data:
  metadata_path: /home/yuwenhan/Tikz/evaluate/save_eval/datikz_test_data/test_metadata.json
  base_dir: /home/yuwenhan/Tikz/evaluate/save_eval

# 生成参数
gen:
  temperature: 0.7
  max_new_tokens: 1024

# 运行控制
run:
  max_attempts: 3       # 递归修复最多尝试次数
  limit: 5              # 仅处理前 N 条；为 null/删除该项则处理全部

# 输出目录
outputs:
  json_dir: output/original-output-inputwithimg
  tex_dir: output/output-tex-inputwithimg
  pdf_dir: save/pdf
  png_dir: save/png
  log_dir: save/log